// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Routine.Date;

namespace Routine.Migrations
{
    [DbContext(typeof(RoutineDbContext))]
    partial class RoutineDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Routine.Entity.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Introduction")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5067c167-122d-464c-ac95-40322fae31d2"),
                            Introduction = "Great Company",
                            Name = "Microsoft"
                        },
                        new
                        {
                            Id = new Guid("f0ba734d-c62b-4e28-8d54-9e4c2d7dd94e"),
                            Introduction = "alipay",
                            Name = "ALIBABA"
                        },
                        new
                        {
                            Id = new Guid("2f9e2e78-96b1-4203-b4e9-87764f8ee601"),
                            Introduction = "Do not be evil",
                            Name = "Google"
                        });
                });

            modelBuilder.Entity("Routine.Entity.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("47008320-99f6-4064-87d9-1e0316c4c181"),
                            CompanyId = new Guid("2f9e2e78-96b1-4203-b4e9-87764f8ee601"),
                            DateOfBirth = new DateTime(1994, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeNo = "1",
                            FirstName = "光",
                            Gender = 1,
                            LastName = "李"
                        },
                        new
                        {
                            Id = new Guid("1c18c214-d921-4edf-8629-c5046eb4e67d"),
                            CompanyId = new Guid("2f9e2e78-96b1-4203-b4e9-87764f8ee601"),
                            DateOfBirth = new DateTime(1987, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeNo = "2",
                            FirstName = "三",
                            Gender = 1,
                            LastName = "张"
                        },
                        new
                        {
                            Id = new Guid("5896c321-b223-4509-bdd0-291199260cf1"),
                            CompanyId = new Guid("5067c167-122d-464c-ac95-40322fae31d2"),
                            DateOfBirth = new DateTime(1990, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeNo = "3",
                            FirstName = "四",
                            Gender = 2,
                            LastName = "李"
                        },
                        new
                        {
                            Id = new Guid("2149a84e-2cbe-428c-98e6-6856f15f1515"),
                            CompanyId = new Guid("5067c167-122d-464c-ac95-40322fae31d2"),
                            DateOfBirth = new DateTime(1990, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeNo = "4",
                            FirstName = "六",
                            Gender = 2,
                            LastName = "赵"
                        });
                });

            modelBuilder.Entity("Routine.Entity.Employee", b =>
                {
                    b.HasOne("Routine.Entity.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Routine.Entity.Company", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
